#!/bin/bash
yum update -y
yum install nginx -y
systemctl start nginx
systemctl enable nginx
aws s3 cp s3://amit-costomer-bucket/index.html /usr/share/nginx/html/
mkdir -p /var/www/html
ln -s /usr/share/nginx/html/* /var/www/html/
